/**
 * Rendering of the environment files that expose workshop variables to
 * terminals. Each variable becomes an upper-cased environment variable,
 * and the built-in variables are prefixed with `WORKSHOP_`.
 */

import { Variables, shellQuote } from './substitute';

/** Built-in variable names, which are exported with a `WORKSHOP_` prefix. */
export const BUILTIN_VARIABLES: readonly string[] = [
  'platform',
  'shell',
  'path_sep',
  'workshop_dir',
  'home',
  'user',
  'lite',
  'hub'
];

/**
 * Map workshop variables to environment variable names and values.
 */
export function environmentVariables(
  variables: Variables
): Record<string, string> {
  const result: Record<string, string> = {};

  for (const [name, value] of Object.entries(variables)) {
    const upper = name.toUpperCase();

    result[BUILTIN_VARIABLES.includes(name) ? `WORKSHOP_${upper}` : upper] =
      value;
  }

  return result;
}

/**
 * Render a POSIX shell file that exports the variables.
 */
export function renderEnvSh(variables: Variables): string {
  const lines = ['# Generated by the workshop extension. Do not edit.'];

  for (const [name, value] of Object.entries(environmentVariables(variables))) {
    lines.push(`export ${name}=${shellQuote(value)}`);
  }

  return `${lines.join('\n')}\n`;
}

/**
 * Render a PowerShell file that sets the variables.
 */
export function renderEnvPs1(variables: Variables): string {
  const lines = ['# Generated by the workshop extension. Do not edit.'];

  for (const [name, value] of Object.entries(environmentVariables(variables))) {
    lines.push(`$env:${name} = '${value.replace(/'/g, "''")}'`);
  }

  return `${lines.join('\n')}\n`;
}
