/**
 * Rendering of the environment files that expose workshop variables to
 * terminals. Each variable becomes an upper-cased environment variable,
 * and the built-in variables are prefixed with `WORKSHOP_`.
 */

import { Variables, shellQuote } from './substitute';

/** Built-in variable names, which are exported with a `WORKSHOP_` prefix. */
export const BUILTIN_VARIABLES: readonly string[] = [
  'platform',
  'shell',
  'path_sep',
  'workshop_dir',
  'home',
  'user',
  'host',
  'container'
];

/**
 * Map workshop variables to environment variable names and values.
 */
export function environmentVariables(
  variables: Variables
): Record<string, string> {
  const result: Record<string, string> = {};

  for (const [name, value] of Object.entries(variables)) {
    const upper = name.toUpperCase();

    result[BUILTIN_VARIABLES.includes(name) ? `WORKSHOP_${upper}` : upper] =
      value;
  }

  return result;
}

/**
 * The environment exported to workshop terminals: the variables, then
 * the manifest's `env` mapping, which wins where the names clash.
 */
export function terminalEnvironment(
  variables: Variables,
  env: Readonly<Record<string, string>> = {}
): Record<string, string> {
  return { ...environmentVariables(variables), ...env };
}

/**
 * Render a POSIX shell file that exports the variables.
 */
export function renderEnvSh(
  variables: Variables,
  env: Readonly<Record<string, string>> = {}
): string {
  const lines = ['# Generated by the workshop extension. Do not edit.'];

  for (const [name, value] of Object.entries(
    terminalEnvironment(variables, env)
  )) {
    lines.push(`export ${name}=${shellQuote(value)}`);
  }

  return `${lines.join('\n')}\n`;
}

/**
 * Render a Windows command prompt batch file that sets the variables.
 */
export function renderEnvCmd(
  variables: Variables,
  env: Readonly<Record<string, string>> = {}
): string {
  const lines = [
    '@echo off',
    'rem Generated by the workshop extension. Do not edit.'
  ];

  for (const [name, value] of Object.entries(
    terminalEnvironment(variables, env)
  )) {
    // Quoting the whole assignment keeps special characters literal; the
    // quotes themselves are not part of the value.
    lines.push(`set "${name}=${value.replace(/"/g, '')}"`);
  }

  return `${lines.join('\r\n')}\r\n`;
}

/**
 * Render a PowerShell file that sets the variables.
 */
export function renderEnvPs1(
  variables: Variables,
  env: Readonly<Record<string, string>> = {}
): string {
  const lines = ['# Generated by the workshop extension. Do not edit.'];

  for (const [name, value] of Object.entries(
    terminalEnvironment(variables, env)
  )) {
    lines.push(`$env:${name} = '${value.replace(/'/g, "''")}'`);
  }

  return `${lines.join('\n')}\n`;
}
