/**
 * Rendering of the environment files that expose workshop variables to
 * terminals. Each variable becomes an upper-cased environment variable,
 * and the built-in variables are prefixed with `WORKSHOP_`.
 */

import { Variables, shellQuote } from './substitute';

/** Built-in variable names, which are exported with a `WORKSHOP_` prefix. */
export const BUILTIN_VARIABLES: readonly string[] = [
  'platform',
  'shell',
  'path_sep',
  'workshop_dir',
  'home',
  'user',
  'host',
  'container'
];

/**
 * Map workshop variables to environment variable names and values.
 */
export function environmentVariables(
  variables: Variables
): Record<string, string> {
  const result: Record<string, string> = {};

  for (const [name, value] of Object.entries(variables)) {
    const upper = name.toUpperCase();

    result[BUILTIN_VARIABLES.includes(name) ? `WORKSHOP_${upper}` : upper] =
      value;
  }

  return result;
}

/**
 * A workshop environment to put on a terminal's PATH: the virtual
 * environment's directory and the directory of its programs.
 */
export interface IVenvExports {
  root: string;
  bin: string;
}

/**
 * The environment exported to workshop terminals: the variables, then
 * the manifest's `env` mapping, which wins where the names clash.
 */
export function terminalEnvironment(
  variables: Variables,
  env: Readonly<Record<string, string>> = {}
): Record<string, string> {
  return { ...environmentVariables(variables), ...env };
}

/**
 * Render a POSIX shell file that exports the variables.
 */
export function renderEnvSh(
  variables: Variables,
  env: Readonly<Record<string, string>> = {},
  venv?: IVenvExports
): string {
  const lines = ['# Generated by the workshop extension. Do not edit.'];

  for (const [name, value] of Object.entries(
    terminalEnvironment(variables, env)
  )) {
    lines.push(`export ${name}=${shellQuote(value)}`);
  }

  // The workshop environment goes first on PATH, as activating it would
  // put it, and VIRTUAL_ENV names it for tools and prompts that look.
  if (venv) {
    lines.push(`export VIRTUAL_ENV=${shellQuote(venv.root)}`);
    lines.push(`export PATH=${shellQuote(venv.bin)}:"$PATH"`);
  }

  return `${lines.join('\n')}\n`;
}

/**
 * Render a Windows command prompt batch file that sets the variables.
 */
export function renderEnvCmd(
  variables: Variables,
  env: Readonly<Record<string, string>> = {},
  venv?: IVenvExports
): string {
  const lines = [
    '@echo off',
    'rem Generated by the workshop extension. Do not edit.'
  ];

  for (const [name, value] of Object.entries(
    terminalEnvironment(variables, env)
  )) {
    // Quoting the whole assignment keeps special characters literal; the
    // quotes themselves are not part of the value.
    lines.push(`set "${name}=${value.replace(/"/g, '')}"`);
  }

  if (venv) {
    lines.push(`set "VIRTUAL_ENV=${venv.root.replace(/"/g, '')}"`);
    lines.push(`set "PATH=${venv.bin.replace(/"/g, '')};%PATH%"`);
  }

  return `${lines.join('\r\n')}\r\n`;
}

/**
 * Render a PowerShell file that sets the variables.
 */
export function renderEnvPs1(
  variables: Variables,
  env: Readonly<Record<string, string>> = {},
  venv?: IVenvExports
): string {
  const lines = ['# Generated by the workshop extension. Do not edit.'];

  for (const [name, value] of Object.entries(
    terminalEnvironment(variables, env)
  )) {
    lines.push(`$env:${name} = '${value.replace(/'/g, "''")}'`);
  }

  // PowerShell runs on every platform, so the separator is asked for.
  if (venv) {
    lines.push(`$env:VIRTUAL_ENV = '${venv.root.replace(/'/g, "''")}'`);
    lines.push(
      `$env:PATH = '${venv.bin.replace(/'/g, "''")}' + [IO.Path]::PathSeparator + $env:PATH`
    );
  }

  return `${lines.join('\n')}\n`;
}
