import {
  environmentVariables,
  renderEnvPs1,
  renderEnvSh
} from '../variables/envfile';

const variables = {
  platform: 'macos',
  workshop_dir: 'examples/git',
  repo_dir: "it's",
  token: ''
};

describe('environment files', () => {
  it('prefixes built-ins and upper-cases names', () => {
    expect(environmentVariables(variables)).toEqual({
      WORKSHOP_PLATFORM: 'macos',
      WORKSHOP_WORKSHOP_DIR: 'examples/git',
      REPO_DIR: "it's",
      TOKEN: ''
    });
  });

  it('renders a POSIX file with quoting', () => {
    expect(renderEnvSh(variables)).toBe(
      "# Generated by the workshop extension. Do not edit.\nexport WORKSHOP_PLATFORM=macos\nexport WORKSHOP_WORKSHOP_DIR=examples/git\nexport REPO_DIR='it'\\''s'\nexport TOKEN=''\n"
    );
  });

  it('renders a PowerShell file with doubled quotes', () => {
    expect(renderEnvPs1({ repo_dir: "it's" })).toBe(
      "# Generated by the workshop extension. Do not edit.\n$env:REPO_DIR = 'it''s'\n"
    );
  });
});
