import {
  environmentVariables,
  PromptScanner,
  findPromptMarker,
  renderEnvCmd,
  renderEnvFish,
  renderEnvPs1,
  renderEnvSh,
  terminalEnvironment
} from '../variables/envfile';

const variables = {
  platform: 'macos',
  workshop_dir: 'examples/git',
  repo_dir: "it's",
  token: ''
};

describe('environment files', () => {
  it('prefixes built-ins and upper-cases names', () => {
    expect(environmentVariables(variables)).toEqual({
      WORKSHOP_PLATFORM: 'macos',
      WORKSHOP_WORKSHOP_DIR: 'examples/git',
      REPO_DIR: "it's",
      TOKEN: ''
    });
  });

  it('adds the manifest environment after the variables', () => {
    expect(terminalEnvironment({ token: 'x' })).toEqual({ TOKEN: 'x' });
    expect(
      terminalEnvironment({ token: 'x' }, { PAGER: 'cat', TOKEN: 'y' })
    ).toEqual({ TOKEN: 'y', PAGER: 'cat' });
  });

  it('renders a POSIX file with quoting', () => {
    expect(renderEnvSh(variables)).toBe(
      "# Generated by the workshop extension. Do not edit.\nexport WORKSHOP_PLATFORM=macos\nexport WORKSHOP_WORKSHOP_DIR=examples/git\nexport REPO_DIR='it'\\''s'\nexport TOKEN=''\n"
    );
  });

  it('renders a PowerShell file with doubled quotes', () => {
    expect(renderEnvPs1({ repo_dir: "it's" })).toBe(
      "# Generated by the workshop extension. Do not edit.\n$env:REPO_DIR = 'it''s'\n"
    );
  });

  it('renders a batch file with quoted assignments', () => {
    expect(renderEnvCmd({ repo_dir: 'it"s & more' })).toBe(
      '@echo off\r\nrem Generated by the workshop extension. Do not edit.\r\nset "REPO_DIR=its & more"\r\n'
    );
  });
});

describe('workshop environment on PATH', () => {
  const venv = { root: '/w/_workshop/venv', bin: '/w/_workshop/venv/bin' };

  it('exports VIRTUAL_ENV and prefixes PATH in each shell', () => {
    expect(renderEnvSh({}, {}, venv)).toBe(
      '# Generated by the workshop extension. Do not edit.\nexport VIRTUAL_ENV=/w/_workshop/venv\nexport PATH=/w/_workshop/venv/bin:"$PATH"\n'
    );
    expect(renderEnvPs1({}, {}, venv)).toContain(
      "$env:PATH = '/w/_workshop/venv/bin' + [IO.Path]::PathSeparator + $env:PATH"
    );
    expect(renderEnvCmd({}, {}, venv)).toContain(
      'set "PATH=/w/_workshop/venv/bin;%PATH%"'
    );
  });

  it('leaves the files alone without one', () => {
    expect(renderEnvSh({})).not.toContain('PATH');
    expect(renderEnvPs1({})).not.toContain('PATH');
    expect(renderEnvCmd({})).not.toContain('PATH');
  });
});

describe('the workshop prompt', () => {
  const prompt = { root: '/w/work' };

  it('installs the marked prompt in the POSIX file without control bytes', () => {
    const text = renderEnvSh({}, {}, undefined, prompt);

    expect(text).toContain(
      'export WORKSHOP_PROMPT_ROOT="$(cd /w/work 2>/dev/null && pwd -P || printf \'%s\' /w/work)"'
    );
    expect(text).toContain(
      '__workshop_osc="$(printf \'\\033]7770;workshop;\')"'
    );
    expect(text).toContain(
      "PROMPT_COMMAND='__workshop_status=$?; __workshop_serial=$((__workshop_serial+1))'"
    );
    expect(text).toContain(
      'precmd() { __workshop_status=$?; __workshop_serial=$((__workshop_serial+1)); }'
    );
    expect(text).toContain("eval 'precmd_functions=()'");
    expect(text).toContain("printf '\\033[H\\033[2J\\033[3J'");
    expect(text).not.toMatch(/[\x1b\x07]/);
  });

  it('renders the fish, PowerShell and batch prompts', () => {
    const fish = renderEnvFish({ repo_dir: "it's" }, {}, undefined, prompt);

    expect(fish).toContain("set -gx REPO_DIR 'it\\'s'");
    expect(fish).toContain(
      "printf '\\e]7770;workshop;%s;%s\\a%s $ ' $code $__workshop_serial $dir"
    );
    expect(renderEnvPs1({}, {}, undefined, prompt)).toContain(
      '$global:WorkshopPromptSerial += 1'
    );
    expect(renderEnvCmd({}, {}, undefined, prompt)).toContain(
      'set "PROMPT=$E]7770;workshop;0$E\\$P$G "'
    );
  });

  it('puts the environment on the fish PATH as a list', () => {
    expect(
      renderEnvFish({}, {}, { root: '/w/venv', bin: '/w/venv/bin' })
    ).toContain("set -gx PATH '/w/venv/bin' $PATH");
  });

  it('leaves the prompt out when none is asked for', () => {
    expect(renderEnvSh({})).not.toContain('PS1');
    expect(renderEnvFish({})).not.toContain('fish_prompt');
    expect(renderEnvPs1({})).not.toContain('prompt');
    expect(renderEnvCmd({})).not.toContain('PROMPT');
  });
});

describe('prompt markers', () => {
  it('finds a marker with either terminator, its status and serial', () => {
    expect(findPromptMarker('abc\x1b]7770;workshop;1;12\x07~ $ ')).toEqual({
      status: 1,
      serial: 12,
      end: 24
    });
    expect(findPromptMarker('\x1b]7770;workshop;0\x1b\\$ ')).toEqual({
      status: 0,
      serial: null,
      end: 19
    });
  });

  it('ignores an incomplete marker', () => {
    expect(findPromptMarker('\x1b]7770;workshop;')).toBeNull();
    expect(findPromptMarker('~ $ ')).toBeNull();
  });

  it('scans markers split across chunks', () => {
    const scanner = new PromptScanner();

    expect(scanner.feed('out\x1b]7770;work')).toEqual([]);
    expect(scanner.feed('shop;0;1\x07~ $ ').map(m => m.serial)).toEqual([1]);
  });

  it('drops a prompt drawn again but not a continuation prompt', () => {
    const scanner = new PromptScanner();
    const prompt = (serial: number): string =>
      `\x1b]7770;workshop;0;${serial}\x07~ $ `;
    const continuation = '\x1b]7770;workshop;0\x07> ';

    expect(scanner.feed(prompt(3)).length).toBe(1);
    expect(scanner.feed(`\r${prompt(3)}`)).toEqual([]);
    expect(
      scanner.feed(`${continuation}${continuation}${prompt(4)}`).length
    ).toBe(3);
    expect(scanner.feed(prompt(2))).toEqual([]);
  });
});
